title: Renting Bikes on Koh Samui
description: >-
  Tips, routes, and local know-how for renting scooters & bikes on Koh Samui,
  from the team at samui-bikes.com.
url: https://samuibikes.github.io
baseurl: /samui-bikes-pages
theme: minima
permalink: /:year/:month/:day/:title/
future: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
